name: Deploy App Service

on:
  push:
    branches:
      - master

  workflow_dispatch:

env:
  Configuration: 'Release'
  ProjectPath: 'TestTask.API/TestTask.API.csproj'
  BuildPath: 'outputs/src'
  ArtifactName: 'drop'
  WebAppName: 'mytesttask'

jobs:
  build-dotnet:
    name: Run Build and Test .NET
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET 7.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Transform appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: 'TestTask.API/appsettings.json'
        env:
          Config.ConnectionString: ${{ secrets.DATABASE_URL }}
          Config.JwtSignGuid: ${{ secrets.JWT_SIGN_KEY }}

      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Build .NET Solution
        run: |
          dotnet build --no-restore /p:ContinuousIntegrationBuild=true --configuration $Configuration
      - name: Run .NET Publish
        run: |
          dotnet publish $ProjectPath --configuration $Configuration --output $BuildPath --no-build
      - name: Drop Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.ArtifactName }}"
          path: "${{ env.BuildPath }}"
  
  deploy:
    needs: [ build-dotnet ]
    name: Deploy App Service
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "${{ env.ArtifactName }}"
          path: "${{ env.BuildPath }}"

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ env.WebAppName }}"
          publish-profile: "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}"
          package: "${{ env.BuildPath }}"