on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Azure ARM
    steps:

    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.RG_NAME }}
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters/parameters.dev.json adminUser=${{ secrets.SQL_ADMIN }} adminPassword=${{ secrets.SQL_PASSWORD }}
        failOnStdErr: false
